[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "pyscad"
version = "0.0.1"
authors = [
    { name="Tarah Tamayo", email="kabittarah@gmail.com" },
]
description = "Kabit's PythonSCAD Generators and Tools"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"